name: '0xdabbad00'
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 1
safe: true
lsi: false
permalink: pretty
