name: '0xdabbad00'
url: http://0xdabbad00.com
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
safe: true
lsi: false
permalink: pretty
excerpt_separator: "\r\n\r\n\r\n"
